# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: '/'
    weight: 10
  - name: Corsi
    weight: 20
    identifier: corso
  - name: Corso introduttivo a R
    PageRef: course/corso-intro-r/_index.md
    weight: 10
    parent: corso
  # - name: Materiale
  #   PageRef: course/materiale/_index.md
  #   weight: 20
  #   parent: corso
  - name: Blog
    PageRef: post/_index.md
    weight: 30
  - name: Contatti
    PageRef: contact/index.md
    weight: 60
